// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPLTHD_BE.Models;

public partial class Adsadvertisingpicture
{
    public int Id { get; set; }

    public byte[] HinhAnh { get; set; }

    public int? AdsAdvertisingId { get; set; }

    public virtual Adsadvertising AdsAdvertising { get; set; }
}