// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPLTHD_BE.Models;

public partial class Adslocation
{
    public int Id { get; set; }

    public string AdsAddress { get; set; }

    public float? Width { get; set; }

    public float? Height { get; set; }

    public string SizeUnit { get; set; }

    public int? Quantity { get; set; }

    public decimal? Latitute { get; set; }

    public decimal? Longtitute { get; set; }

    public int? TypeAds { get; set; }

    public int? Status { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreateOnUtc { get; set; }

    public DateTime? LastUpdateOnUtc { get; set; }

    public int? CreateUserId { get; set; }

    public int? UpdateUserId { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Adsadvertising> Adsadvertisings { get; set; } = new List<Adsadvertising>();

    public virtual ICollection<Adslocationpicture> Adslocationpictures { get; set; } = new List<Adslocationpicture>();

    public virtual ICollection<Adslocationupdate> Adslocationupdates { get; set; } = new List<Adslocationupdate>();

    public virtual ICollection<Reportwarning> Reportwarnings { get; set; } = new List<Reportwarning>();
}