// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Adslocationpicture
{
    public int Id { get; set; }

    public byte[] HinhAnh { get; set; }

    public int? AdsLocationId { get; set; }

    public virtual Adslocation AdsLocation { get; set; }
}