// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Adslocationupdate
{
    public int AdsLocationUpdateId { get; set; }

    public int? AdsLocationId { get; set; }

    public DateTime? Date { get; set; }

    public string Comment { get; set; }

    public string StatusEdit { get; set; }

    public DateTime? CreateOnUtc { get; set; }

    public DateTime? LastUpdateOnUtc { get; set; }

    public int? CreateUserId { get; set; }

    public int? UpdateUserId { get; set; }

    public ulong IsActive { get; set; }
}