// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPLTHD_BE.Models;

public partial class Adslocationupdate
{
    public int Id { get; set; }

    public int? AdsLocationId { get; set; }

    public DateTime? Date { get; set; }

    public string Comment { get; set; }

    public int? OldStatus { get; set; }

    public int? NewStatus { get; set; }

    public DateTime? CreateOnUtc { get; set; }

    public int? CreateUserId { get; set; }

    public virtual Adslocation AdsLocation { get; set; }
}