// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Adslocationimage
{
    public int AdsLocationImageId { get; set; }

    public byte[] Image { get; set; }

    public int? AdsLocationId { get; set; }

    public DateTime? CreateOnUtc { get; set; }

    public int? CreateUserId { get; set; }
}