// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Adsnewpicture
{
    public int Id { get; set; }

    public byte[] HinhAnh { get; set; }

    public int? AdsNewId { get; set; }
}