// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Adsstatus
{
    public int AdsStatusId { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public DateTime? CreateOnUtc { get; set; }

    public DateTime? LastUpdateOnUtc { get; set; }

    public int? CreateUserId { get; set; }

    public int? UpdateUserId { get; set; }

    public bool IsActive { get; set; }
}