// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Aspnetuserrole
{
    public string UserId { get; set; }

    public string RoleId { get; set; }

    public virtual Aspnetrole Role { get; set; }

    public virtual Aspnetuser User { get; set; }
}