// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Efmigrationshistory
{
    public string MigrationId { get; set; }

    public string ProductVersion { get; set; }
}