// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Log
{
    public int Id { get; set; }

    public string Timestamp { get; set; }

    public string Level { get; set; }

    public string Template { get; set; }

    public string Message { get; set; }

    public string Exception { get; set; }

    public string Properties { get; set; }

    public DateTime? Ts { get; set; }
}