// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Reportwarning
{
    public int Id { get; set; }

    public int? WarmType { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Comment { get; set; }

    public int? AdsLocationId { get; set; }

    public int? Status { get; set; }

    public DateTime? CreateOnUtc { get; set; }

    public DateTime? LastUpdateOnUtc { get; set; }

    public int? CreateUserId { get; set; }

    public int? UpdateUserId { get; set; }

    public ulong IsActive { get; set; }

    public virtual Adslocation AdsLocation { get; set; }

    public virtual ICollection<Reportwarningurl> Reportwarningurls { get; set; } = new List<Reportwarningurl>();
}