// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GovBE.Models;

public partial class Reportwarningurl
{
    public int Id { get; set; }

    public int? ReportWarningId { get; set; }

    public string Url { get; set; }

    public DateTime? CreateOnUtc { get; set; }

    public int? CreateUserId { get; set; }
}